### ISSUE TITLE
Bad Mipmapping in Panorama

### ISSUE THREAD

**Issue by bestsoft100** [EmulatedVattic/EM32D#1]
In Minecraft there's an issue with mipmapping that causes the side of grass blocks to look bad, and its very visible in the panorama.

![2021-12-20_21 07 53](https://user-images.githubusercontent.com/49400900/146826680-d2678a6e-5744-4121-a11d-a7a494dcd86d.png)

This could be fixed by installing OptiFine, or by disabling mipmapping.

**Comment by 3vorp** [comment]
fixed in latest commit
